version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: legend
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234567890
      MYSQL_CHARSET: 'utf8mb4'
      MYSQL_COLLATION: 'utf8mb4_unicode_ci'
    ports:
      - "3306:3306"
    volumes:
      - ./01_create_gifts.sql:/docker-entrypoint-initdb.d/01_create_gifts.sql
      - ./02_gifts_data.sql:/docker-entrypoint-initdb.d/02_gifts_data.sql
      - ./03_create_campaigns.sql:/docker-entrypoint-initdb.d/03_create_campaigns.sql
      - ./04_campaigns_data.sql:/docker-entrypoint-initdb.d/04_campaigns_data.sql

volumes:
  mydb: